### ISSUE TITLE
Package removed from PackageControl

### ISSUE THREAD

**Issue by ycanales** [ctf0/Yeti_UX#2]
Your theme was recommended on Sublime Text Tips newsletter and couldn't find it in Package Control in Sublime Text. Visiting the PackageControl page says it's been removed.

Thought you might want to know.

![screen shot 2017-06-22 at 14 08 45](https://user-images.githubusercontent.com/2023360/27448869-63da371e-5754-11e7-97e3-4a552a4d32ff.png)

**Comment by ctf0** [comment]
ah yes, sadly i've removed it because there wasnt much traffic on it and it was hard for me to keep supporting it along with seti_ux.
